version: '3.8'
services:
  my5grantester:
    image: my5grantester:latest
    container_name: my5grantester
    privileged: true
    entrypoint: /bin/bash -c "sleep infinity"
    volumes:
      - ./config.yml:/my5G-RANTester/config/config.yml
    environment:
      NGAP_LOCAL_ADDR: 172.26.0.252
      NGAP_REMOTE_ADDR: 172.26.0.12 # AMF IP ADDR
      GTPU_LOCAL_ADDR: 172.26.0.252
      MCC: "001"
      MNC: "01"
      TAC: "3039"
      GNBID: "000001"
      SST_GNB: "01"
      SST_UE: "01"
      SD: "1691105"
      MSIN: "0000000003"
      OPC: 8baf473f2f8fd09487cccbd7097c6862
      KEY: 8e27b6af0e692e750f32667a3b14605d
      AMF: "8000"
      SQN: "0000000"
      DNN: internet
      NUM_UE: 1
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
          ipv4_address: 172.26.0.252
    healthcheck:
      test: /bin/bash -c "ip addr | grep uetun1"
      interval: 10s
      timeout: 5s
      retries: 5
 
networks:
    privnet:      # Using existing network of core network
        external:
            name: docker_vingc_net