apiVersion: v1
kind: Service
metadata:
  name: ue
  namespace: ns-enterprise1
spec:
  selector:
    app: ue
  ports:
    - protocol: TCP
      port: 2001         # Port that the service will expose
      targetPort: 2001    # Port on the pod that the service will route traffic to
  type: ClusterIP       # Internal service accessible only within the cluster
