apiVersion: v1
kind: Service
metadata:
  name: gnb
  namespace: ns-enterprise1
spec:
  selector:
    app: gnb
  ports:
    - protocol: TCP
      port: 2000         # Port that the service will expose
      targetPort: 2000    # Port on the pod that the service will route traffic to
  type: ClusterIP       # Internal service accessible only within the cluster
